CREATE TABLE IF NOT EXISTS movies (
  movie_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  tmdb_id INTEGER UNIQUE NOT NULL,
  description TEXT NOT NULL,
  release_date TEXT NOT NULL,
  popularity NUMERIC NOT NULL,
  poster TEXT,
  avg_vote NUMERIC,
  vote_count NUMERIC
);