CREATE TABLE IF NOT EXISTS user_lists (
  user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
  list_id INTEGER REFERENCES lists(list_id) ON DELETE CASCADE ON UPDATE CASCADE
);